name: build

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip code
        run: unzip -o material-news.zip
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: material-news/site
          github_token: ${{ secrets.GITHUB_TOKEN }}
